#!/usr/bin/env zsh

if [[ ${0[0]} = '/' ]]; then
    scriptdir="${0:h}"
else
    scriptdir="$PWD/${0:h}"
fi

{
cat head.html
for slide in slide-*.html; do
    print -- '<section class="slide">'
    cat $slide
    print -- '</section>'
done
cat tail.html
} > $scriptdir/../categories.html
