#!/usr/bin/env zsh

# get script directory
if [[ ${0[0]} = '/' ]]; then
    scriptdir="${0:h}"
else
    scriptdir="$PWD/${0:h}"
fi

cd $scriptdir

# Convert all slides from markdown
for slide in slide-*.md(.N); do
    pandoc -f markdown -t html $slide > ${slide:r}.html
done

{
cat head.html
for slide in slide-*.html(.N); do
    print -- '<section class="slide">'
    cat $slide | sed 's#&amp;#<span class="and">&</span>#g'
    print -- '</section>'
done
cat tail.html
} > ../categories.html
